version: '3.8'

services:
  my-app:
    # build: .
    image: tweedoriginal/docker-tutorial:1.0
    ports:
      - 3000:3000
    environment:
      MONGO_DB_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_DB_PWD: ${MONGO_DB_PWD}
    depends_on:  
      - "mongodb"  

  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PWD}
    ports:
      - '27017:27017'

  mongoexpress:
    image: mongo-express
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_DB_PWD}
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:  
      - "mongodb"

